Repository IceButler/IceButler_Web, pull requests merged in 2023-06, with the labels that each got.

#66 #65 불필요한 주석문 제거
  netlify.toml
  src/components/Sidebar/Sidebar.js
  src/pages/Email/Email.js
  src/pages/UserManage/UserManage.js
Labels: ♻️ refactor

#68 #67 feat: netlify.toml 세팅
  netlify.toml
  src/pages/FoodManage/FoodManage.js
Labels: ⚙ infra

#69 #67 feat: netlify.toml 세팅
  netlify.toml
Labels: ⚙ infra

#70 #67 feat: netlify.toml 세팅
  netlify.toml
  src/pages/Login/Login.js
Labels: ⚙ infra

#71 #67 feat: netlify.toml 세팅
  src/pages/Login/Login.js
Labels: ⚙ infra

#72 #67 feat: netlify proxy 설정
  netlify.toml
  src/pages/Email/WithdrawEmail.js
  src/pages/FoodManage/FoodManage.js
  src/pages/FoodManage/FoodTr.js
  src/pages/Login/Login.js
  src/pages/ReportManage/CompleteReportManage.js
  src/pages/ReportManage/ReportDetail/ReportDetail.js
  src/pages/ReportManage/ReportManage.js
  src/pages/UserManage/UserManage.js
  src/pages/UserManage/WithdrawUserManage.js
Labels: ⚙ infra

#73 #65 페이지 이동 경로 수정
  src/App.js
Labels: 🔨fix

#74 #67 feat: netlify proxy 설정
  src/pages/FoodManage/FoodManage.js
  src/pages/FoodManage/FoodTr.js
Labels: ⚙ infra

#75 #21 식품 관리 페이지 에러 해결
  src/pages/FoodManage/FoodManage.js
  src/pages/FoodManage/FoodTr.js
Labels: 🔨fix

#76 #67 env 파일 생성 및 적용
  netlify.toml
  src/setupProxy.js
Labels: 🍽 feature, 🔨fix

#77 #67 s3 프록시 설정
  netlify.toml
  src/pages/FoodManage/FoodTr.js
Labels: 🍽 feature, 🔨fix

#78 #21 카테고리 에러 수정
  src/pages/FoodManage/FoodTr.js
Labels: 🚑 hotfix

#81 #80 예외처리 statuscode 수정
  src/components/Sidebar/Sidebar.js
  src/pages/Email/WithdrawEmail.js
  src/pages/FoodManage/FoodManage.js
  src/pages/FoodManage/FoodTr.js
  src/pages/ReportManage/CompleteReportManage.js
  src/pages/ReportManage/ReportDetail/ReportDetail.js
  src/pages/ReportManage/ReportManage.js
  src/pages/UserManage/UserManage.js
  src/pages/UserManage/WithdrawUserManage.js
Labels: ♻️ refactor
